GET  http://hiking-backend.germangorodnev.com/hikes

###
POST http://hiking-backend.germangorodnev.com/hikes/filteredHikes
content-type: application/json

{
    "province": "Salerno",
    "region": null,
    "maxLength": 15,
    "minLength": 5,
    "expectedTimeMin": null,
    "expectedTimeMax": null,
    "difficultyMin": null,
    "difficultyMax": null,
    "ascentMin": null,
    "ascentMax": null
}

###
POST http://hiking-backend.germangorodnev.com/hikes/import
content-type: multipart/form-data

{
    "gpxFile": null,
    "title": "test",
    "description": "loremipsum"
}
